### PR TITLE
WIP: Enable Switch PowerShell Exe

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This exposes a function `SwitchPowerShellExecutable` that will prompt you for which PowerShell version you want to work on.

I haven't tested this on Windows yet... but let me know what you think so far.

image

cc @corbob

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
🤔 Must be the extra slashes?

**Comment by yatli** [comment]
can confirm. working on it.

**Comment by yatli** [comment]
should be working now; @corbob could you test it out?

**Comment by TylerLeonhardt** [comment]
I'd like to change this up a bit... let me mess with it this weekend.

**Comment by TylerLeonhardt** [comment]
Closing this in favor of #16

**Pull request closed without merging**
