### PR TITLE
Move to TypeScript

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
fixes https://github.com/yatli/coc-powershell/issues/17

TODO:
* [x] get it working
* [x] make paths dynamic
* [x] move download of PSES to ts
* [x] ~figure out where to set `rtp` so coc can discover coc-powershell~ - coc's package manager provides this, so we should be fine.
* [ ] rename the lang id from ps1 to powershell (maybe defer)
* [ ] build and release pipeline to npm
* [x] ~figure out how to get coc to discover coc-powershell npm package~ - coc's package manager will handle this.

### CODE REVIEW

**Comment by yatli** [comment]
okay, extension loads properly now with set rtp^=.
the next task is to download PSES, and optionally show a progress bar for this.

**Comment by corbob** [comment]
Nice, I tried to copy over the extension.ts and package.json from coc-fsharp, but my `tsc` runs were causing errors.

**Comment by yatli** [comment]
@corbob I was getting erros, so I updated the package versions in `package.json` and ran `npm install` and it's fixed (not sure why)

**Comment by TylerLeonhardt** [comment]
ok updated with this working for me. We only have a couple things left to do here. Feel free to pick up one if you'd like.

**Comment by corbob** [comment]
I think once it's in npm, then coc finds it if I understand correctly.

Am I correct in my understanding that to install it you would simply `:CocInstall <Full Path to local repository>`? Do we need to rev the version number to test changes (I was reving it last night and then doing `:CocUpdate` to get an update, but that might not be needed?)

**Comment by TylerLeonhardt** [comment]
nope. For me, it just worked when I removed the Plug entry and just had:

```
set rtp^=/path/to/coc-powershell
```

**Comment by yatli** [comment]
>  figure out where to set rtp so coc can discover coc-powershell

If you use the coc plugin manager, it'll be downloaded from npm and discovered automatically.
There are two ways of doing this:
1. use `:CocInstall coc-powershell`
2. add to your vimrc: `let g:coc_global_extensions=[ 'coc-powershell', ... ]`

**Comment by yatli** [comment]
>  rename the lang id from ps1 to powershell (maybe defer)

I prefer to stay with `set filetype=ps1` because there are other components relying on this id -- syntax highlight, indent rules, etc.
Most notably, people may use `vim-polyglot` or https://github.com/PProvost/vim-ps1.

**Comment by TylerLeonhardt** [comment]
So I've made a change to have ts run the `install.ps1`. My reasoning:

* PowerShell is already needed so we can leverage it
* PowerShell's download & unzip APIs are much more intuitive and supported than Node.js's are

Let me know what you think. I'm leveraging the `node-powershell` package.

**Comment by yatli** [comment]
Looks cool! The whole automation process is very smooth.
I've added a few bits so that coc-powershell starts to take advantage of coc features.
For example:

coc-powershell

**Comment by yatli** [comment]
note, I've created an output channel for `coc-powershell`.
use `logger.appendLine` to output to `:CocInfo` panel

**Pull request merged**
